#EXIT THE SERVER USING COMMAND "exit" THEN SSH BACK INTO THE SERVER
#THIS HAS TO BE DONE BECAUSE THE ENVIRONMENT VARIABLES WON'T BE SET UNLESS
#YOU LOGOUT THEN LOG BACK IN
#THEN YOU GET BACK IN AND STOP THE index.js PROCESS, AND START IT AGAIN
#I REALIZE THAT IT'S BETTER IF I DO THIS WHOLE LOGOUT AND LOG BACK IN AFTER I
#SET MY ENV VARIABLES IMMEDIATELY WHICH WOULD SPARE THE STEPS OF HAVING TO STOP #AND START THE BACKEND API, BUT I ONLY DID IT THIS WAY IN THIS SCRIPT
#TO MAKE THE FIRST SCRIPT DO MOST OF THE WORK, TO BE SAFE IN CASE YOU 
#DIDN'T NOTICE THAT THIS SMALL SCRIPT EXISTED
cd /opt/BackEnd/src
pm2 stop 0
pm2 delete 0
pm2 start index.js --watch
pm2 save
